---
apiVersion: v1
kind: Namespace
metadata:
  name: stockExchange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: stockExchange
  name: stockExchange-deploy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: stockExchange-app
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stockExchange-app
    spec:
      containers:
        - image: anushka20211064/stockxchangetool:latest
          imagePullPolicy: Always
          name: stockExchange-app
          ports:
            - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  namespace: stockExchange
  name: stockExchange-service
spec:
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: stockExchange-app
  type: LoadBalancer
status:
  loadBalancer: {}
