name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      run: docker login --username "${{ secrets.DOCKER_USERNAME }}" --password "${{ secrets.DOCKER_PASSWORD }}"
      
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag stockexchange_test/v1
	  
    - name: Tag the Docker Image
      run: docker tag stockexchange_test/v1 anushka20211064/stockxchangetool
      
    - name: Push the Docker Image
      run: docker push anushka20211064/stockxchangetool
